version: "3"
services:
  donkey:
    # build: .    # uncomment this if you want to build from dockerfile
    build: .
    hostname: donkey_1 # Rename this to Racer2 Racer3 to avoid duplicated names showing in mobile app
    container_name: donkeycar
    ports:
      - "8000:8000"
      - "8887:8887"
      - "8886:8886"
    stdin_open: true # docker run -i
    tty: true
    volumes:
      - ./mycar:/root/mycar
      - ./donkeycar/donkeycar:/root/donkeycar/donkeycar
    environment:
      - mode=docker
